// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file FieldDTO.proto

import Foundation
import ProtocolBuffers


internal func == (lhs: FieldDto, rhs: FieldDto) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasId == rhs.hasId) && (!lhs.hasId || lhs.id == rhs.id)
  fieldCheck = fieldCheck && (lhs.hasName == rhs.hasName) && (!lhs.hasName || lhs.name == rhs.name)
  fieldCheck = fieldCheck && (lhs.hasLongitude == rhs.hasLongitude) && (!lhs.hasLongitude || lhs.longitude == rhs.longitude)
  fieldCheck = fieldCheck && (lhs.hasLatitude == rhs.hasLatitude) && (!lhs.hasLatitude || lhs.latitude == rhs.latitude)
  fieldCheck = fieldCheck && (lhs.hasSport == rhs.hasSport) && (!lhs.hasSport || lhs.sport == rhs.sport)
  fieldCheck = fieldCheck && (lhs.hasAddress == rhs.hasAddress) && (!lhs.hasAddress || lhs.address == rhs.address)
  fieldCheck = fieldCheck && (lhs.hasDescription == rhs.hasDescription) && (!lhs.hasDescription || lhs.description_ == rhs.description_)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal struct FieldDtoRoot {
  internal static var sharedInstance : FieldDtoRoot {
   struct Static {
       static let instance : FieldDtoRoot = FieldDtoRoot()
   }
   return Static.instance
  }
  internal var extensionRegistry:ExtensionRegistry

  init() {
    extensionRegistry = ExtensionRegistry()
    registerAllExtensions(extensionRegistry)
  }
  internal func registerAllExtensions(registry:ExtensionRegistry) {
  }
}

final internal class FieldDto : GeneratedMessage, GeneratedMessageProtocol, Hashable {
  private(set) var hasId:Bool = false
  private(set) var id:Int64 = Int64(0)

  private(set) var hasName:Bool = false
  private(set) var name:String = ""

  private(set) var hasDescription:Bool = false
  private(set) var description_:String = ""

  private(set) var hasLongitude:Bool = false
  private(set) var longitude:Double = Double(0)

  private(set) var hasLatitude:Bool = false
  private(set) var latitude:Double = Double(0)

  private(set) var hasSport:Bool = false
  private(set) var sport:Int64 = Int64(0)

  private(set) var hasAddress:Bool = false
  private(set) var address:String = ""

  required internal init() {
       super.init()
  }
  override internal func isInitialized() -> Bool {
   return true
  }
  override internal func writeToCodedOutputStream(output:CodedOutputStream) {
    if hasId {
      output.writeInt64(1, value:id)
    }
    if hasName {
      output.writeString(2, value:name)
    }
    if hasLongitude {
      output.writeDouble(3, value:longitude)
    }
    if hasLatitude {
      output.writeDouble(4, value:latitude)
    }
    if hasSport {
      output.writeInt64(5, value:sport)
    }
    if hasAddress {
      output.writeString(6, value:address)
    }
    if hasDescription {
      output.writeString(19, value:description_)
    }
    unknownFields.writeToCodedOutputStream(output)
  }
  override internal func serializedSize() -> Int32 {
    var serialize_size:Int32 = memoizedSerializedSize
    if serialize_size != -1 {
     return serialize_size
    }

    serialize_size = 0
    if hasId {
      serialize_size += id.computeInt64Size(1)
    }
    if hasName {
      serialize_size += name.computeStringSize(2)
    }
    if hasLongitude {
      serialize_size += longitude.computeDoubleSize(3)
    }
    if hasLatitude {
      serialize_size += latitude.computeDoubleSize(4)
    }
    if hasSport {
      serialize_size += sport.computeInt64Size(5)
    }
    if hasAddress {
      serialize_size += address.computeStringSize(6)
    }
    if hasDescription {
      serialize_size += description_.computeStringSize(19)
    }
    serialize_size += unknownFields.serializedSize()
    memoizedSerializedSize = serialize_size
    return serialize_size
  }
  internal class func parseArrayDelimitedFromInputStream(input:NSInputStream) -> Array<FieldDto> {
    var mergedArray = Array<FieldDto>()
    while let value = parseFromDelimitedFromInputStream(input) {
      mergedArray += [value]
    }
    return mergedArray
  }
  internal class func parseFromData(data:NSData) -> FieldDto {
    return FieldDto.Builder().mergeFromData(data, extensionRegistry:FieldDtoRoot.sharedInstance.extensionRegistry).build()
  }
  internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> FieldDto {
    return FieldDto.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromInputStream(input:NSInputStream) -> FieldDto {
    return FieldDto.Builder().mergeFromInputStream(input).build()
  }
  internal class func parseFromDelimitedFromInputStream(input:NSInputStream) -> FieldDto? {
    return FieldDto.Builder().mergeDelimitedFromInputStream(input)?.build()
  }
  internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> FieldDto {
    return FieldDto.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream) -> FieldDto {
    return FieldDto.Builder().mergeFromCodedInputStream(input).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> FieldDto {
    return FieldDto.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func getBuilder() -> FieldDto.Builder {
    return FieldDto.classBuilder() as! FieldDto.Builder
  }
  internal func getBuilder() -> FieldDto.Builder {
    return classBuilder() as! FieldDto.Builder
  }
  internal override class func classBuilder() -> MessageBuilder {
    return FieldDto.Builder()
  }
  internal override func classBuilder() -> MessageBuilder {
    return FieldDto.Builder()
  }
  internal func toBuilder() -> FieldDto.Builder {
    return FieldDto.builderWithPrototype(self)
  }
  internal class func builderWithPrototype(prototype:FieldDto) -> FieldDto.Builder {
    return FieldDto.Builder().mergeFrom(prototype)
  }
  override internal func writeDescriptionTo(inout output:String, indent:String) {
    if hasId {
      output += "\(indent) id: \(id) \n"
    }
    if hasName {
      output += "\(indent) name: \(name) \n"
    }
    if hasLongitude {
      output += "\(indent) longitude: \(longitude) \n"
    }
    if hasLatitude {
      output += "\(indent) latitude: \(latitude) \n"
    }
    if hasSport {
      output += "\(indent) sport: \(sport) \n"
    }
    if hasAddress {
      output += "\(indent) address: \(address) \n"
    }
    if hasDescription {
      output += "\(indent) description_: \(description_) \n"
    }
    unknownFields.writeDescriptionTo(&output, indent:indent)
  }
  override internal var hashValue:Int {
      get {
          var hashCode:Int = 7
          if hasId {
             hashCode = (hashCode &* 31) &+ id.hashValue
          }
          if hasName {
             hashCode = (hashCode &* 31) &+ name.hashValue
          }
          if hasLongitude {
             hashCode = (hashCode &* 31) &+ longitude.hashValue
          }
          if hasLatitude {
             hashCode = (hashCode &* 31) &+ latitude.hashValue
          }
          if hasSport {
             hashCode = (hashCode &* 31) &+ sport.hashValue
          }
          if hasAddress {
             hashCode = (hashCode &* 31) &+ address.hashValue
          }
          if hasDescription {
             hashCode = (hashCode &* 31) &+ description_.hashValue
          }
          hashCode = (hashCode &* 31) &+  unknownFields.hashValue
          return hashCode
      }
  }


  //Meta information declaration start

  override internal class func className() -> String {
      return "FieldDto"
  }
  override internal func className() -> String {
      return "FieldDto"
  }
  override internal func classMetaType() -> GeneratedMessage.Type {
      return FieldDto.self
  }
  //Meta information declaration end

  final internal class Builder : GeneratedMessageBuilder {
    private var builderResult:FieldDto = FieldDto()
    internal func getMessage() -> FieldDto {
        return builderResult
    }

    required override internal init () {
       super.init()
    }
    var hasId:Bool {
         get {
              return builderResult.hasId
         }
    }
    var id:Int64 {
         get {
              return builderResult.id
         }
         set (value) {
             builderResult.hasId = true
             builderResult.id = value
         }
    }
    func setId(value:Int64) -> FieldDto.Builder {
      self.id = value
      return self
    }
    internal func clearId() -> FieldDto.Builder{
         builderResult.hasId = false
         builderResult.id = Int64(0)
         return self
    }
    var hasName:Bool {
         get {
              return builderResult.hasName
         }
    }
    var name:String {
         get {
              return builderResult.name
         }
         set (value) {
             builderResult.hasName = true
             builderResult.name = value
         }
    }
    func setName(value:String) -> FieldDto.Builder {
      self.name = value
      return self
    }
    internal func clearName() -> FieldDto.Builder{
         builderResult.hasName = false
         builderResult.name = ""
         return self
    }
    var hasDescription:Bool {
         get {
              return builderResult.hasDescription
         }
    }
    var description_:String {
         get {
              return builderResult.description_
         }
         set (value) {
             builderResult.hasDescription = true
             builderResult.description_ = value
         }
    }
    func setDescription(value:String) -> FieldDto.Builder {
      self.description_ = value
      return self
    }
    internal func clearDescription() -> FieldDto.Builder{
         builderResult.hasDescription = false
         builderResult.description_ = ""
         return self
    }
    var hasLongitude:Bool {
         get {
              return builderResult.hasLongitude
         }
    }
    var longitude:Double {
         get {
              return builderResult.longitude
         }
         set (value) {
             builderResult.hasLongitude = true
             builderResult.longitude = value
         }
    }
    func setLongitude(value:Double) -> FieldDto.Builder {
      self.longitude = value
      return self
    }
    internal func clearLongitude() -> FieldDto.Builder{
         builderResult.hasLongitude = false
         builderResult.longitude = Double(0)
         return self
    }
    var hasLatitude:Bool {
         get {
              return builderResult.hasLatitude
         }
    }
    var latitude:Double {
         get {
              return builderResult.latitude
         }
         set (value) {
             builderResult.hasLatitude = true
             builderResult.latitude = value
         }
    }
    func setLatitude(value:Double) -> FieldDto.Builder {
      self.latitude = value
      return self
    }
    internal func clearLatitude() -> FieldDto.Builder{
         builderResult.hasLatitude = false
         builderResult.latitude = Double(0)
         return self
    }
    var hasSport:Bool {
         get {
              return builderResult.hasSport
         }
    }
    var sport:Int64 {
         get {
              return builderResult.sport
         }
         set (value) {
             builderResult.hasSport = true
             builderResult.sport = value
         }
    }
    func setSport(value:Int64) -> FieldDto.Builder {
      self.sport = value
      return self
    }
    internal func clearSport() -> FieldDto.Builder{
         builderResult.hasSport = false
         builderResult.sport = Int64(0)
         return self
    }
    var hasAddress:Bool {
         get {
              return builderResult.hasAddress
         }
    }
    var address:String {
         get {
              return builderResult.address
         }
         set (value) {
             builderResult.hasAddress = true
             builderResult.address = value
         }
    }
    func setAddress(value:String) -> FieldDto.Builder {
      self.address = value
      return self
    }
    internal func clearAddress() -> FieldDto.Builder{
         builderResult.hasAddress = false
         builderResult.address = ""
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> FieldDto.Builder {
      builderResult = FieldDto()
      return self
    }
    internal override func clone() -> FieldDto.Builder {
      return FieldDto.builderWithPrototype(builderResult)
    }
    internal override func build() -> FieldDto {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> FieldDto {
      var returnMe:FieldDto = builderResult
      return returnMe
    }
    internal func mergeFrom(other:FieldDto) -> FieldDto.Builder {
      if other == FieldDto() {
       return self
      }
      if other.hasId {
           id = other.id
      }
      if other.hasName {
           name = other.name
      }
      if other.hasDescription {
           description_ = other.description_
      }
      if other.hasLongitude {
           longitude = other.longitude
      }
      if other.hasLatitude {
           latitude = other.latitude
      }
      if other.hasSport {
           sport = other.sport
      }
      if other.hasAddress {
           address = other.address
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) -> FieldDto.Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> FieldDto.Builder {
      var unknownFieldsBuilder:UnknownFieldSet.Builder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          id = input.readInt64()

        case 18 :
          name = input.readString()

        case 25 :
          longitude = input.readDouble()

        case 33 :
          latitude = input.readDouble()

        case 40 :
          sport = input.readInt64()

        case 50 :
          address = input.readString()

        case 154 :
          description_ = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}


// @@protoc_insertion_point(global_scope)
