// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file LeagueDTO.proto

import Foundation
import ProtocolBuffers


internal func == (lhs: LeagueDto, rhs: LeagueDto) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasId == rhs.hasId) && (!lhs.hasId || lhs.id == rhs.id)
  fieldCheck = fieldCheck && (lhs.hasName == rhs.hasName) && (!lhs.hasName || lhs.name == rhs.name)
  fieldCheck = fieldCheck && (lhs.hasRegion == rhs.hasRegion) && (!lhs.hasRegion || lhs.region == rhs.region)
  fieldCheck = fieldCheck && (lhs.teams == rhs.teams)
  fieldCheck = fieldCheck && (lhs.hasDescription == rhs.hasDescription) && (!lhs.hasDescription || lhs.description_ == rhs.description_)
  fieldCheck = fieldCheck && (lhs.hasLogo == rhs.hasLogo) && (!lhs.hasLogo || lhs.logo == rhs.logo)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal struct LeagueDtoRoot {
  internal static var sharedInstance : LeagueDtoRoot {
   struct Static {
       static let instance : LeagueDtoRoot = LeagueDtoRoot()
   }
   return Static.instance
  }
  internal var extensionRegistry:ExtensionRegistry

  init() {
    extensionRegistry = ExtensionRegistry()
    registerAllExtensions(extensionRegistry)
    TeamDtoRoot.sharedInstance.registerAllExtensions(extensionRegistry)
  }
  internal func registerAllExtensions(registry:ExtensionRegistry) {
  }
}

final internal class LeagueDto : GeneratedMessage, GeneratedMessageProtocol, Hashable {
  private(set) var hasId:Bool = false
  private(set) var id:Int64 = Int64(0)

  private(set) var hasName:Bool = false
  private(set) var name:String = ""

  private(set) var hasRegion:Bool = false
  private(set) var region:Int32 = Int32(0)

  private(set) var teams:Array<TeamDto>  = Array<TeamDto>()
  private(set) var hasDescription:Bool = false
  private(set) var description_:String = ""

  private(set) var hasLogo:Bool = false
  private(set) var logo:String = ""

  required internal init() {
       super.init()
  }
  override internal func isInitialized() -> Bool {
   return true
  }
  override internal func writeToCodedOutputStream(output:CodedOutputStream) {
    if hasId {
      output.writeInt64(1, value:id)
    }
    if hasName {
      output.writeString(2, value:name)
    }
    if hasRegion {
      output.writeInt32(3, value:region)
    }
    for oneElementteams in teams {
        output.writeMessage(4, value:oneElementteams)
    }
    if hasDescription {
      output.writeString(16, value:description_)
    }
    if hasLogo {
      output.writeString(17, value:logo)
    }
    unknownFields.writeToCodedOutputStream(output)
  }
  override internal func serializedSize() -> Int32 {
    var serialize_size:Int32 = memoizedSerializedSize
    if serialize_size != -1 {
     return serialize_size
    }

    serialize_size = 0
    if hasId {
      serialize_size += id.computeInt64Size(1)
    }
    if hasName {
      serialize_size += name.computeStringSize(2)
    }
    if hasRegion {
      serialize_size += region.computeInt32Size(3)
    }
    for oneElementteams in teams {
        serialize_size += oneElementteams.computeMessageSize(4)
    }
    if hasDescription {
      serialize_size += description_.computeStringSize(16)
    }
    if hasLogo {
      serialize_size += logo.computeStringSize(17)
    }
    serialize_size += unknownFields.serializedSize()
    memoizedSerializedSize = serialize_size
    return serialize_size
  }
  internal class func parseArrayDelimitedFromInputStream(input:NSInputStream) -> Array<LeagueDto> {
    var mergedArray = Array<LeagueDto>()
    while let value = parseFromDelimitedFromInputStream(input) {
      mergedArray += [value]
    }
    return mergedArray
  }
  internal class func parseFromData(data:NSData) -> LeagueDto {
    return LeagueDto.Builder().mergeFromData(data, extensionRegistry:LeagueDtoRoot.sharedInstance.extensionRegistry).build()
  }
  internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> LeagueDto {
    return LeagueDto.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromInputStream(input:NSInputStream) -> LeagueDto {
    return LeagueDto.Builder().mergeFromInputStream(input).build()
  }
  internal class func parseFromDelimitedFromInputStream(input:NSInputStream) -> LeagueDto? {
    return LeagueDto.Builder().mergeDelimitedFromInputStream(input)?.build()
  }
  internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> LeagueDto {
    return LeagueDto.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream) -> LeagueDto {
    return LeagueDto.Builder().mergeFromCodedInputStream(input).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> LeagueDto {
    return LeagueDto.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func getBuilder() -> LeagueDto.Builder {
    return LeagueDto.classBuilder() as! LeagueDto.Builder
  }
  internal func getBuilder() -> LeagueDto.Builder {
    return classBuilder() as! LeagueDto.Builder
  }
  internal override class func classBuilder() -> MessageBuilder {
    return LeagueDto.Builder()
  }
  internal override func classBuilder() -> MessageBuilder {
    return LeagueDto.Builder()
  }
  internal func toBuilder() -> LeagueDto.Builder {
    return LeagueDto.builderWithPrototype(self)
  }
  internal class func builderWithPrototype(prototype:LeagueDto) -> LeagueDto.Builder {
    return LeagueDto.Builder().mergeFrom(prototype)
  }
  override internal func writeDescriptionTo(inout output:String, indent:String) {
    if hasId {
      output += "\(indent) id: \(id) \n"
    }
    if hasName {
      output += "\(indent) name: \(name) \n"
    }
    if hasRegion {
      output += "\(indent) region: \(region) \n"
    }
    var teamsElementIndex:Int = 0
    for oneElementteams in teams {
        output += "\(indent) teams[\(teamsElementIndex)] {\n"
        oneElementteams.writeDescriptionTo(&output, indent:"\(indent)  ")
        output += "\(indent)}\n"
        teamsElementIndex++
    }
    if hasDescription {
      output += "\(indent) description_: \(description_) \n"
    }
    if hasLogo {
      output += "\(indent) logo: \(logo) \n"
    }
    unknownFields.writeDescriptionTo(&output, indent:indent)
  }
  override internal var hashValue:Int {
      get {
          var hashCode:Int = 7
          if hasId {
             hashCode = (hashCode &* 31) &+ id.hashValue
          }
          if hasName {
             hashCode = (hashCode &* 31) &+ name.hashValue
          }
          if hasRegion {
             hashCode = (hashCode &* 31) &+ region.hashValue
          }
          for oneElementteams in teams {
              hashCode = (hashCode &* 31) &+ oneElementteams.hashValue
          }
          if hasDescription {
             hashCode = (hashCode &* 31) &+ description_.hashValue
          }
          if hasLogo {
             hashCode = (hashCode &* 31) &+ logo.hashValue
          }
          hashCode = (hashCode &* 31) &+  unknownFields.hashValue
          return hashCode
      }
  }


  //Meta information declaration start

  override internal class func className() -> String {
      return "LeagueDto"
  }
  override internal func className() -> String {
      return "LeagueDto"
  }
  override internal func classMetaType() -> GeneratedMessage.Type {
      return LeagueDto.self
  }
  //Meta information declaration end

  final internal class Builder : GeneratedMessageBuilder {
    private var builderResult:LeagueDto = LeagueDto()
    internal func getMessage() -> LeagueDto {
        return builderResult
    }

    required override internal init () {
       super.init()
    }
    var hasId:Bool {
         get {
              return builderResult.hasId
         }
    }
    var id:Int64 {
         get {
              return builderResult.id
         }
         set (value) {
             builderResult.hasId = true
             builderResult.id = value
         }
    }
    func setId(value:Int64) -> LeagueDto.Builder {
      self.id = value
      return self
    }
    internal func clearId() -> LeagueDto.Builder{
         builderResult.hasId = false
         builderResult.id = Int64(0)
         return self
    }
    var hasName:Bool {
         get {
              return builderResult.hasName
         }
    }
    var name:String {
         get {
              return builderResult.name
         }
         set (value) {
             builderResult.hasName = true
             builderResult.name = value
         }
    }
    func setName(value:String) -> LeagueDto.Builder {
      self.name = value
      return self
    }
    internal func clearName() -> LeagueDto.Builder{
         builderResult.hasName = false
         builderResult.name = ""
         return self
    }
    var hasRegion:Bool {
         get {
              return builderResult.hasRegion
         }
    }
    var region:Int32 {
         get {
              return builderResult.region
         }
         set (value) {
             builderResult.hasRegion = true
             builderResult.region = value
         }
    }
    func setRegion(value:Int32) -> LeagueDto.Builder {
      self.region = value
      return self
    }
    internal func clearRegion() -> LeagueDto.Builder{
         builderResult.hasRegion = false
         builderResult.region = Int32(0)
         return self
    }
    var teams:Array<TeamDto> {
         get {
             return builderResult.teams
         }
         set (value) {
             builderResult.teams = value
         }
    }
    func setTeams(value:Array<TeamDto>) -> LeagueDto.Builder {
      self.teams = value
      return self
    }
    internal func clearTeams() -> LeagueDto.Builder {
      builderResult.teams.removeAll(keepCapacity: false)
      return self
    }
    var hasDescription:Bool {
         get {
              return builderResult.hasDescription
         }
    }
    var description_:String {
         get {
              return builderResult.description_
         }
         set (value) {
             builderResult.hasDescription = true
             builderResult.description_ = value
         }
    }
    func setDescription(value:String) -> LeagueDto.Builder {
      self.description_ = value
      return self
    }
    internal func clearDescription() -> LeagueDto.Builder{
         builderResult.hasDescription = false
         builderResult.description_ = ""
         return self
    }
    var hasLogo:Bool {
         get {
              return builderResult.hasLogo
         }
    }
    var logo:String {
         get {
              return builderResult.logo
         }
         set (value) {
             builderResult.hasLogo = true
             builderResult.logo = value
         }
    }
    func setLogo(value:String) -> LeagueDto.Builder {
      self.logo = value
      return self
    }
    internal func clearLogo() -> LeagueDto.Builder{
         builderResult.hasLogo = false
         builderResult.logo = ""
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> LeagueDto.Builder {
      builderResult = LeagueDto()
      return self
    }
    internal override func clone() -> LeagueDto.Builder {
      return LeagueDto.builderWithPrototype(builderResult)
    }
    internal override func build() -> LeagueDto {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> LeagueDto {
      var returnMe:LeagueDto = builderResult
      return returnMe
    }
    internal func mergeFrom(other:LeagueDto) -> LeagueDto.Builder {
      if other == LeagueDto() {
       return self
      }
      if other.hasId {
           id = other.id
      }
      if other.hasName {
           name = other.name
      }
      if other.hasRegion {
           region = other.region
      }
      if !other.teams.isEmpty  {
         builderResult.teams += other.teams
      }
      if other.hasDescription {
           description_ = other.description_
      }
      if other.hasLogo {
           logo = other.logo
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) -> LeagueDto.Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> LeagueDto.Builder {
      var unknownFieldsBuilder:UnknownFieldSet.Builder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          id = input.readInt64()

        case 18 :
          name = input.readString()

        case 24 :
          region = input.readInt32()

        case 34 :
          var subBuilder = TeamDto.Builder()
          input.readMessage(subBuilder,extensionRegistry:extensionRegistry)
          teams += [subBuilder.buildPartial()]

        case 130 :
          description_ = input.readString()

        case 138 :
          logo = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}


// @@protoc_insertion_point(global_scope)
