// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file NotificationListDTO.proto

import Foundation
import ProtocolBuffers


internal func == (lhs: NotificationListDto, rhs: NotificationListDto) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.items == rhs.items)
  fieldCheck = fieldCheck && (lhs.hasPageNumber == rhs.hasPageNumber) && (!lhs.hasPageNumber || lhs.pageNumber == rhs.pageNumber)
  fieldCheck = fieldCheck && (lhs.hasPageTotal == rhs.hasPageTotal) && (!lhs.hasPageTotal || lhs.pageTotal == rhs.pageTotal)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal struct NotificationListDtoRoot {
  internal static var sharedInstance : NotificationListDtoRoot {
   struct Static {
       static let instance : NotificationListDtoRoot = NotificationListDtoRoot()
   }
   return Static.instance
  }
  internal var extensionRegistry:ExtensionRegistry

  init() {
    extensionRegistry = ExtensionRegistry()
    registerAllExtensions(extensionRegistry)
    NotificationDtoRoot.sharedInstance.registerAllExtensions(extensionRegistry)
  }
  internal func registerAllExtensions(registry:ExtensionRegistry) {
  }
}

final internal class NotificationListDto : GeneratedMessage, GeneratedMessageProtocol, Hashable {
  private(set) var items:Array<NotificationDto>  = Array<NotificationDto>()
  private(set) var hasPageNumber:Bool = false
  private(set) var pageNumber:Int32 = Int32(0)

  private(set) var hasPageTotal:Bool = false
  private(set) var pageTotal:Int32 = Int32(0)

  required internal init() {
       super.init()
  }
  override internal func isInitialized() -> Bool {
   return true
  }
  override internal func writeToCodedOutputStream(output:CodedOutputStream) {
    for oneElementitems in items {
        output.writeMessage(1, value:oneElementitems)
    }
    if hasPageNumber {
      output.writeInt32(2, value:pageNumber)
    }
    if hasPageTotal {
      output.writeInt32(3, value:pageTotal)
    }
    unknownFields.writeToCodedOutputStream(output)
  }
  override internal func serializedSize() -> Int32 {
    var serialize_size:Int32 = memoizedSerializedSize
    if serialize_size != -1 {
     return serialize_size
    }

    serialize_size = 0
    for oneElementitems in items {
        serialize_size += oneElementitems.computeMessageSize(1)
    }
    if hasPageNumber {
      serialize_size += pageNumber.computeInt32Size(2)
    }
    if hasPageTotal {
      serialize_size += pageTotal.computeInt32Size(3)
    }
    serialize_size += unknownFields.serializedSize()
    memoizedSerializedSize = serialize_size
    return serialize_size
  }
  internal class func parseArrayDelimitedFromInputStream(input:NSInputStream) -> Array<NotificationListDto> {
    var mergedArray = Array<NotificationListDto>()
    while let value = parseFromDelimitedFromInputStream(input) {
      mergedArray += [value]
    }
    return mergedArray
  }
  internal class func parseFromData(data:NSData) -> NotificationListDto {
    return NotificationListDto.Builder().mergeFromData(data, extensionRegistry:NotificationListDtoRoot.sharedInstance.extensionRegistry).build()
  }
  internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> NotificationListDto {
    return NotificationListDto.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromInputStream(input:NSInputStream) -> NotificationListDto {
    return NotificationListDto.Builder().mergeFromInputStream(input).build()
  }
  internal class func parseFromDelimitedFromInputStream(input:NSInputStream) -> NotificationListDto? {
    return NotificationListDto.Builder().mergeDelimitedFromInputStream(input)?.build()
  }
  internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> NotificationListDto {
    return NotificationListDto.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream) -> NotificationListDto {
    return NotificationListDto.Builder().mergeFromCodedInputStream(input).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> NotificationListDto {
    return NotificationListDto.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func getBuilder() -> NotificationListDto.Builder {
    return NotificationListDto.classBuilder() as! NotificationListDto.Builder
  }
  internal func getBuilder() -> NotificationListDto.Builder {
    return classBuilder() as! NotificationListDto.Builder
  }
  internal override class func classBuilder() -> MessageBuilder {
    return NotificationListDto.Builder()
  }
  internal override func classBuilder() -> MessageBuilder {
    return NotificationListDto.Builder()
  }
  internal func toBuilder() -> NotificationListDto.Builder {
    return NotificationListDto.builderWithPrototype(self)
  }
  internal class func builderWithPrototype(prototype:NotificationListDto) -> NotificationListDto.Builder {
    return NotificationListDto.Builder().mergeFrom(prototype)
  }
  override internal func writeDescriptionTo(inout output:String, indent:String) {
    var itemsElementIndex:Int = 0
    for oneElementitems in items {
        output += "\(indent) items[\(itemsElementIndex)] {\n"
        oneElementitems.writeDescriptionTo(&output, indent:"\(indent)  ")
        output += "\(indent)}\n"
        itemsElementIndex++
    }
    if hasPageNumber {
      output += "\(indent) pageNumber: \(pageNumber) \n"
    }
    if hasPageTotal {
      output += "\(indent) pageTotal: \(pageTotal) \n"
    }
    unknownFields.writeDescriptionTo(&output, indent:indent)
  }
  override internal var hashValue:Int {
      get {
          var hashCode:Int = 7
          for oneElementitems in items {
              hashCode = (hashCode &* 31) &+ oneElementitems.hashValue
          }
          if hasPageNumber {
             hashCode = (hashCode &* 31) &+ pageNumber.hashValue
          }
          if hasPageTotal {
             hashCode = (hashCode &* 31) &+ pageTotal.hashValue
          }
          hashCode = (hashCode &* 31) &+  unknownFields.hashValue
          return hashCode
      }
  }


  //Meta information declaration start

  override internal class func className() -> String {
      return "NotificationListDto"
  }
  override internal func className() -> String {
      return "NotificationListDto"
  }
  override internal func classMetaType() -> GeneratedMessage.Type {
      return NotificationListDto.self
  }
  //Meta information declaration end

  final internal class Builder : GeneratedMessageBuilder {
    private var builderResult:NotificationListDto = NotificationListDto()
    internal func getMessage() -> NotificationListDto {
        return builderResult
    }

    required override internal init () {
       super.init()
    }
    var items:Array<NotificationDto> {
         get {
             return builderResult.items
         }
         set (value) {
             builderResult.items = value
         }
    }
    func setItems(value:Array<NotificationDto>) -> NotificationListDto.Builder {
      self.items = value
      return self
    }
    internal func clearItems() -> NotificationListDto.Builder {
      builderResult.items.removeAll(keepCapacity: false)
      return self
    }
    var hasPageNumber:Bool {
         get {
              return builderResult.hasPageNumber
         }
    }
    var pageNumber:Int32 {
         get {
              return builderResult.pageNumber
         }
         set (value) {
             builderResult.hasPageNumber = true
             builderResult.pageNumber = value
         }
    }
    func setPageNumber(value:Int32) -> NotificationListDto.Builder {
      self.pageNumber = value
      return self
    }
    internal func clearPageNumber() -> NotificationListDto.Builder{
         builderResult.hasPageNumber = false
         builderResult.pageNumber = Int32(0)
         return self
    }
    var hasPageTotal:Bool {
         get {
              return builderResult.hasPageTotal
         }
    }
    var pageTotal:Int32 {
         get {
              return builderResult.pageTotal
         }
         set (value) {
             builderResult.hasPageTotal = true
             builderResult.pageTotal = value
         }
    }
    func setPageTotal(value:Int32) -> NotificationListDto.Builder {
      self.pageTotal = value
      return self
    }
    internal func clearPageTotal() -> NotificationListDto.Builder{
         builderResult.hasPageTotal = false
         builderResult.pageTotal = Int32(0)
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> NotificationListDto.Builder {
      builderResult = NotificationListDto()
      return self
    }
    internal override func clone() -> NotificationListDto.Builder {
      return NotificationListDto.builderWithPrototype(builderResult)
    }
    internal override func build() -> NotificationListDto {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> NotificationListDto {
      var returnMe:NotificationListDto = builderResult
      return returnMe
    }
    internal func mergeFrom(other:NotificationListDto) -> NotificationListDto.Builder {
      if other == NotificationListDto() {
       return self
      }
      if !other.items.isEmpty  {
         builderResult.items += other.items
      }
      if other.hasPageNumber {
           pageNumber = other.pageNumber
      }
      if other.hasPageTotal {
           pageTotal = other.pageTotal
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) -> NotificationListDto.Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> NotificationListDto.Builder {
      var unknownFieldsBuilder:UnknownFieldSet.Builder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 10 :
          var subBuilder = NotificationDto.Builder()
          input.readMessage(subBuilder,extensionRegistry:extensionRegistry)
          items += [subBuilder.buildPartial()]

        case 16 :
          pageNumber = input.readInt32()

        case 24 :
          pageTotal = input.readInt32()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}


// @@protoc_insertion_point(global_scope)
