// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file SeasonDTO.proto

import Foundation
import ProtocolBuffers


internal func == (lhs: SeasonDto, rhs: SeasonDto) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasId == rhs.hasId) && (!lhs.hasId || lhs.id == rhs.id)
  fieldCheck = fieldCheck && (lhs.hasLeague == rhs.hasLeague) && (!lhs.hasLeague || lhs.league == rhs.league)
  fieldCheck = fieldCheck && (lhs.hasTitle == rhs.hasTitle) && (!lhs.hasTitle || lhs.title == rhs.title)
  fieldCheck = fieldCheck && (lhs.scoreTableResult == rhs.scoreTableResult)
  fieldCheck = fieldCheck && (lhs.weeks == rhs.weeks)
  fieldCheck = fieldCheck && (lhs.hasDescription == rhs.hasDescription) && (!lhs.hasDescription || lhs.description_ == rhs.description_)
  fieldCheck = fieldCheck && (lhs.hasDateFrom == rhs.hasDateFrom) && (!lhs.hasDateFrom || lhs.dateFrom == rhs.dateFrom)
  fieldCheck = fieldCheck && (lhs.hasDateTo == rhs.hasDateTo) && (!lhs.hasDateTo || lhs.dateTo == rhs.dateTo)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal struct SeasonDtoRoot {
  internal static var sharedInstance : SeasonDtoRoot {
   struct Static {
       static let instance : SeasonDtoRoot = SeasonDtoRoot()
   }
   return Static.instance
  }
  internal var extensionRegistry:ExtensionRegistry

  init() {
    extensionRegistry = ExtensionRegistry()
    registerAllExtensions(extensionRegistry)
    ScoreTableResultDtoRoot.sharedInstance.registerAllExtensions(extensionRegistry)
    WeekDtoRoot.sharedInstance.registerAllExtensions(extensionRegistry)
  }
  internal func registerAllExtensions(registry:ExtensionRegistry) {
  }
}

final internal class SeasonDto : GeneratedMessage, GeneratedMessageProtocol, Hashable {
  private(set) var hasId:Bool = false
  private(set) var id:Int64 = Int64(0)

  private(set) var hasLeague:Bool = false
  private(set) var league:Int64 = Int64(0)

  private(set) var hasTitle:Bool = false
  private(set) var title:String = ""

  private(set) var scoreTableResult:Array<ScoreTableResultDto>  = Array<ScoreTableResultDto>()
  private(set) var weeks:Array<WeekDto>  = Array<WeekDto>()
  private(set) var hasDescription:Bool = false
  private(set) var description_:String = ""

  private(set) var hasDateFrom:Bool = false
  private(set) var dateFrom:String = ""

  private(set) var hasDateTo:Bool = false
  private(set) var dateTo:String = ""

  required internal init() {
       super.init()
  }
  override internal func isInitialized() -> Bool {
   return true
  }
  override internal func writeToCodedOutputStream(output:CodedOutputStream) {
    if hasId {
      output.writeInt64(1, value:id)
    }
    if hasLeague {
      output.writeInt64(2, value:league)
    }
    if hasTitle {
      output.writeString(3, value:title)
    }
    for oneElementscoreTableResult in scoreTableResult {
        output.writeMessage(4, value:oneElementscoreTableResult)
    }
    for oneElementweeks in weeks {
        output.writeMessage(5, value:oneElementweeks)
    }
    if hasDescription {
      output.writeString(16, value:description_)
    }
    if hasDateFrom {
      output.writeString(17, value:dateFrom)
    }
    if hasDateTo {
      output.writeString(18, value:dateTo)
    }
    unknownFields.writeToCodedOutputStream(output)
  }
  override internal func serializedSize() -> Int32 {
    var serialize_size:Int32 = memoizedSerializedSize
    if serialize_size != -1 {
     return serialize_size
    }

    serialize_size = 0
    if hasId {
      serialize_size += id.computeInt64Size(1)
    }
    if hasLeague {
      serialize_size += league.computeInt64Size(2)
    }
    if hasTitle {
      serialize_size += title.computeStringSize(3)
    }
    for oneElementscoreTableResult in scoreTableResult {
        serialize_size += oneElementscoreTableResult.computeMessageSize(4)
    }
    for oneElementweeks in weeks {
        serialize_size += oneElementweeks.computeMessageSize(5)
    }
    if hasDescription {
      serialize_size += description_.computeStringSize(16)
    }
    if hasDateFrom {
      serialize_size += dateFrom.computeStringSize(17)
    }
    if hasDateTo {
      serialize_size += dateTo.computeStringSize(18)
    }
    serialize_size += unknownFields.serializedSize()
    memoizedSerializedSize = serialize_size
    return serialize_size
  }
  internal class func parseArrayDelimitedFromInputStream(input:NSInputStream) -> Array<SeasonDto> {
    var mergedArray = Array<SeasonDto>()
    while let value = parseFromDelimitedFromInputStream(input) {
      mergedArray += [value]
    }
    return mergedArray
  }
  internal class func parseFromData(data:NSData) -> SeasonDto {
    return SeasonDto.Builder().mergeFromData(data, extensionRegistry:SeasonDtoRoot.sharedInstance.extensionRegistry).build()
  }
  internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> SeasonDto {
    return SeasonDto.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromInputStream(input:NSInputStream) -> SeasonDto {
    return SeasonDto.Builder().mergeFromInputStream(input).build()
  }
  internal class func parseFromDelimitedFromInputStream(input:NSInputStream) -> SeasonDto? {
    return SeasonDto.Builder().mergeDelimitedFromInputStream(input)?.build()
  }
  internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> SeasonDto {
    return SeasonDto.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream) -> SeasonDto {
    return SeasonDto.Builder().mergeFromCodedInputStream(input).build()
  }
  internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> SeasonDto {
    return SeasonDto.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
  }
  internal class func getBuilder() -> SeasonDto.Builder {
    return SeasonDto.classBuilder() as! SeasonDto.Builder
  }
  internal func getBuilder() -> SeasonDto.Builder {
    return classBuilder() as! SeasonDto.Builder
  }
  internal override class func classBuilder() -> MessageBuilder {
    return SeasonDto.Builder()
  }
  internal override func classBuilder() -> MessageBuilder {
    return SeasonDto.Builder()
  }
  internal func toBuilder() -> SeasonDto.Builder {
    return SeasonDto.builderWithPrototype(self)
  }
  internal class func builderWithPrototype(prototype:SeasonDto) -> SeasonDto.Builder {
    return SeasonDto.Builder().mergeFrom(prototype)
  }
  override internal func writeDescriptionTo(inout output:String, indent:String) {
    if hasId {
      output += "\(indent) id: \(id) \n"
    }
    if hasLeague {
      output += "\(indent) league: \(league) \n"
    }
    if hasTitle {
      output += "\(indent) title: \(title) \n"
    }
    var scoreTableResultElementIndex:Int = 0
    for oneElementscoreTableResult in scoreTableResult {
        output += "\(indent) scoreTableResult[\(scoreTableResultElementIndex)] {\n"
        oneElementscoreTableResult.writeDescriptionTo(&output, indent:"\(indent)  ")
        output += "\(indent)}\n"
        scoreTableResultElementIndex++
    }
    var weeksElementIndex:Int = 0
    for oneElementweeks in weeks {
        output += "\(indent) weeks[\(weeksElementIndex)] {\n"
        oneElementweeks.writeDescriptionTo(&output, indent:"\(indent)  ")
        output += "\(indent)}\n"
        weeksElementIndex++
    }
    if hasDescription {
      output += "\(indent) description_: \(description_) \n"
    }
    if hasDateFrom {
      output += "\(indent) dateFrom: \(dateFrom) \n"
    }
    if hasDateTo {
      output += "\(indent) dateTo: \(dateTo) \n"
    }
    unknownFields.writeDescriptionTo(&output, indent:indent)
  }
  override internal var hashValue:Int {
      get {
          var hashCode:Int = 7
          if hasId {
             hashCode = (hashCode &* 31) &+ id.hashValue
          }
          if hasLeague {
             hashCode = (hashCode &* 31) &+ league.hashValue
          }
          if hasTitle {
             hashCode = (hashCode &* 31) &+ title.hashValue
          }
          for oneElementscoreTableResult in scoreTableResult {
              hashCode = (hashCode &* 31) &+ oneElementscoreTableResult.hashValue
          }
          for oneElementweeks in weeks {
              hashCode = (hashCode &* 31) &+ oneElementweeks.hashValue
          }
          if hasDescription {
             hashCode = (hashCode &* 31) &+ description_.hashValue
          }
          if hasDateFrom {
             hashCode = (hashCode &* 31) &+ dateFrom.hashValue
          }
          if hasDateTo {
             hashCode = (hashCode &* 31) &+ dateTo.hashValue
          }
          hashCode = (hashCode &* 31) &+  unknownFields.hashValue
          return hashCode
      }
  }


  //Meta information declaration start

  override internal class func className() -> String {
      return "SeasonDto"
  }
  override internal func className() -> String {
      return "SeasonDto"
  }
  override internal func classMetaType() -> GeneratedMessage.Type {
      return SeasonDto.self
  }
  //Meta information declaration end

  final internal class Builder : GeneratedMessageBuilder {
    private var builderResult:SeasonDto = SeasonDto()
    internal func getMessage() -> SeasonDto {
        return builderResult
    }

    required override internal init () {
       super.init()
    }
    var hasId:Bool {
         get {
              return builderResult.hasId
         }
    }
    var id:Int64 {
         get {
              return builderResult.id
         }
         set (value) {
             builderResult.hasId = true
             builderResult.id = value
         }
    }
    func setId(value:Int64) -> SeasonDto.Builder {
      self.id = value
      return self
    }
    internal func clearId() -> SeasonDto.Builder{
         builderResult.hasId = false
         builderResult.id = Int64(0)
         return self
    }
    var hasLeague:Bool {
         get {
              return builderResult.hasLeague
         }
    }
    var league:Int64 {
         get {
              return builderResult.league
         }
         set (value) {
             builderResult.hasLeague = true
             builderResult.league = value
         }
    }
    func setLeague(value:Int64) -> SeasonDto.Builder {
      self.league = value
      return self
    }
    internal func clearLeague() -> SeasonDto.Builder{
         builderResult.hasLeague = false
         builderResult.league = Int64(0)
         return self
    }
    var hasTitle:Bool {
         get {
              return builderResult.hasTitle
         }
    }
    var title:String {
         get {
              return builderResult.title
         }
         set (value) {
             builderResult.hasTitle = true
             builderResult.title = value
         }
    }
    func setTitle(value:String) -> SeasonDto.Builder {
      self.title = value
      return self
    }
    internal func clearTitle() -> SeasonDto.Builder{
         builderResult.hasTitle = false
         builderResult.title = ""
         return self
    }
    var scoreTableResult:Array<ScoreTableResultDto> {
         get {
             return builderResult.scoreTableResult
         }
         set (value) {
             builderResult.scoreTableResult = value
         }
    }
    func setScoreTableResult(value:Array<ScoreTableResultDto>) -> SeasonDto.Builder {
      self.scoreTableResult = value
      return self
    }
    internal func clearScoreTableResult() -> SeasonDto.Builder {
      builderResult.scoreTableResult.removeAll(keepCapacity: false)
      return self
    }
    var weeks:Array<WeekDto> {
         get {
             return builderResult.weeks
         }
         set (value) {
             builderResult.weeks = value
         }
    }
    func setWeeks(value:Array<WeekDto>) -> SeasonDto.Builder {
      self.weeks = value
      return self
    }
    internal func clearWeeks() -> SeasonDto.Builder {
      builderResult.weeks.removeAll(keepCapacity: false)
      return self
    }
    var hasDescription:Bool {
         get {
              return builderResult.hasDescription
         }
    }
    var description_:String {
         get {
              return builderResult.description_
         }
         set (value) {
             builderResult.hasDescription = true
             builderResult.description_ = value
         }
    }
    func setDescription(value:String) -> SeasonDto.Builder {
      self.description_ = value
      return self
    }
    internal func clearDescription() -> SeasonDto.Builder{
         builderResult.hasDescription = false
         builderResult.description_ = ""
         return self
    }
    var hasDateFrom:Bool {
         get {
              return builderResult.hasDateFrom
         }
    }
    var dateFrom:String {
         get {
              return builderResult.dateFrom
         }
         set (value) {
             builderResult.hasDateFrom = true
             builderResult.dateFrom = value
         }
    }
    func setDateFrom(value:String) -> SeasonDto.Builder {
      self.dateFrom = value
      return self
    }
    internal func clearDateFrom() -> SeasonDto.Builder{
         builderResult.hasDateFrom = false
         builderResult.dateFrom = ""
         return self
    }
    var hasDateTo:Bool {
         get {
              return builderResult.hasDateTo
         }
    }
    var dateTo:String {
         get {
              return builderResult.dateTo
         }
         set (value) {
             builderResult.hasDateTo = true
             builderResult.dateTo = value
         }
    }
    func setDateTo(value:String) -> SeasonDto.Builder {
      self.dateTo = value
      return self
    }
    internal func clearDateTo() -> SeasonDto.Builder{
         builderResult.hasDateTo = false
         builderResult.dateTo = ""
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> SeasonDto.Builder {
      builderResult = SeasonDto()
      return self
    }
    internal override func clone() -> SeasonDto.Builder {
      return SeasonDto.builderWithPrototype(builderResult)
    }
    internal override func build() -> SeasonDto {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> SeasonDto {
      var returnMe:SeasonDto = builderResult
      return returnMe
    }
    internal func mergeFrom(other:SeasonDto) -> SeasonDto.Builder {
      if other == SeasonDto() {
       return self
      }
      if other.hasId {
           id = other.id
      }
      if other.hasLeague {
           league = other.league
      }
      if other.hasTitle {
           title = other.title
      }
      if !other.scoreTableResult.isEmpty  {
         builderResult.scoreTableResult += other.scoreTableResult
      }
      if !other.weeks.isEmpty  {
         builderResult.weeks += other.weeks
      }
      if other.hasDescription {
           description_ = other.description_
      }
      if other.hasDateFrom {
           dateFrom = other.dateFrom
      }
      if other.hasDateTo {
           dateTo = other.dateTo
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) -> SeasonDto.Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> SeasonDto.Builder {
      var unknownFieldsBuilder:UnknownFieldSet.Builder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          id = input.readInt64()

        case 16 :
          league = input.readInt64()

        case 26 :
          title = input.readString()

        case 34 :
          var subBuilder = ScoreTableResultDto.Builder()
          input.readMessage(subBuilder,extensionRegistry:extensionRegistry)
          scoreTableResult += [subBuilder.buildPartial()]

        case 42 :
          var subBuilder = WeekDto.Builder()
          input.readMessage(subBuilder,extensionRegistry:extensionRegistry)
          weeks += [subBuilder.buildPartial()]

        case 130 :
          description_ = input.readString()

        case 138 :
          dateFrom = input.readString()

        case 146 :
          dateTo = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}


// @@protoc_insertion_point(global_scope)
